name: dataenv
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas[version='<3']
  - python=3.12
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - ipykernel
  - jupyterlab
  - nibabel
  - nilearn
  - pyarrow
