name: dataenv
channels:
  - defaults
dependencies:
  - python=3.12.12
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - statsmodels
  - ipykernel
  - jupyterlab
  - seaborn
  - pandas
  - nibabel
  - nilearn
prefix: /home/hannahschewe/.conda/envs/dataenv
