name: dataenv
channels:
  - defaults
dependencies:
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python=3.11
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
prefix: C:\Users\Schewe\AppData\Local\anaconda3\envs\dataenv
