name: dataenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.6.0=hd77b12b_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312he06e257_2
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.1.0=pyhcf101f3_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.4=hdf23a24_1
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.2=hcb3a2da_0
  - aws-c-event-stream=0.5.9=h972bbec_2
  - aws-c-http=0.10.10=hb410799_0
  - aws-c-io=0.26.1=h0d5b9f9_1
  - aws-c-mqtt=0.14.0=h833cf40_1
  - aws-c-s3=0.11.5=h9708004_2
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.10=hcb3a2da_0
  - aws-crt-cpp=0.36.0=h15365d6_1
  - aws-sdk-cpp=1.11.606=h867832e_11
  - azure-core-cpp=1.16.2=h49e36cd_0
  - azure-identity-cpp=1.13.3=h5ffce34_1
  - azure-storage-blobs-cpp=12.16.0=hcd625b1_1
  - azure-storage-common-cpp=12.12.0=h5ffce34_1
  - azure-storage-files-datalake-cpp=12.14.0=h1678c0b_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py312h06d0912_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - blas=1.0=mkl
  - bleach=6.3.0=pyhcf101f3_1
  - bleach-with-css=6.3.0=hbca2aae_1
  - brotli-python=1.2.0=py312hc6d9e41_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h214f63a_0
  - cpython=3.12.12=py312hd8ed1ab_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.20=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py312h02ab6af_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyhe01879c_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - kiwisolver=1.4.9=py312h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20260107.1=cxx17_h0eb2380_0
  - libarrow=23.0.1=haed0678_1_cpu
  - libarrow-acero=23.0.1=h7d8d6a5_1_cpu
  - libarrow-compute=23.0.1=h081cd8e_1_cpu
  - libarrow-dataset=23.0.1=h7d8d6a5_1_cpu
  - libarrow-substrait=23.0.1=h524e9bd_1_cpu
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libclang13=14.0.6=default_h77d9078_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.22=h5bf469e_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libglib=2.84.4=hfaec014_0
  - libgoogle-cloud=2.39.0=h01c467a_1
  - libgoogle-cloud-storage=2.39.0=he04ea4c_1
  - libgrpc=1.78.0=h9ff2b3e_1
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - liblzma=5.8.2=hfd05255_0
  - liblzma-devel=5.8.2=hfd05255_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libparquet=23.0.1=h7051d1f_1_cpu
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=6.33.5=h61fc761_0
  - libre2-11=2025.11.05=h04e5de1_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.0=h404307b_0
  - libutf8proc=2.11.3=hb980946_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py312h05f76fc_0
  - matplotlib=3.10.8=py312h2e8e312_0
  - matplotlib-base=3.10.8=py312h26e45b9_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.2.0=pyhcf101f3_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nibabel=5.3.2=pyha770c72_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.4.2=py312h22cce72_0
  - numpy-base=2.4.2=py312h1df51cf_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=h0a1ad0e_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312hc128f0a_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.6=pyhcf101f3_0
  - patsy=1.0.2=py312haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py312h4212202_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.9.2=pyhcf101f3_0
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=23.0.1=py312h12c7521_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py312haa95532_0
  - pyside6=6.7.3=py312h28b127d_1
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_2_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.12.12=hd8ed1ab_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.12=3_cp312
  - pytz=2025.2=py312haa95532_0
  - pywin32=311=py312h829343e_1
  - pywinpty=2.0.15=py312h275cf98_1
  - pyyaml=6.0.3=py312h05f76fc_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtshadertools=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebengine=6.7.3=h3869032_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - re2=2025.11.05=ha104f34_1
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py312hdabe01f_0
  - scikit-learn=1.8.0=np2py312hea30aaf_1
  - scipy=1.17.0=py312h2074b4c_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=2.1.0=pyh6dadd2b_1
  - setuptools=80.10.2=py312haa95532_0
  - six=1.17.0=py312haa95532_0
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.6=py312h196c9fc_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - terminado=0.18.1=pyh6dadd2b_1
  - threadpoolctl=3.5.0=py312h4442805_1
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=hf199647_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py312h02ab6af_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.46.3=py312haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xz=5.8.2=hb6c8415_0
  - xz-tools=5.8.2=hfd05255_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - acres==0.5.0
      - bids-validator==1.14.7.post0
      - bidsschematools==1.2.0
      - click==8.3.1
      - docopt==0.6.2
      - et-xmlfile==2.0.0
      - formulaic==1.2.1
      - frozendict==2.4.7
      - fsspec==2026.2.0
      - greenlet==3.3.1
      - interface-meta==1.3.0
      - lxml==6.0.2
      - narwhals==2.16.0
      - nilearn==0.12.1
      - num2words==0.5.14
      - openpyxl==3.1.5
      - pandas-stubs==3.0.0.260204
      - pathlib-abc==0.5.2
      - pyarrow==23.0.1
      - pybids==0.21.0
      - sqlalchemy==2.0.46
      - templateflow==25.1.1
      - tqdm==4.67.3
      - universal-pathlib==0.3.9
      - wrapt==2.1.1
